### ISSUE TITLE
Agent and UI localization

### ISSUE THREAD

**Issue by elmagnificogi** [ResurrectedTrader/ResurrectedTrade#1] opened 2022-05-10 16:06 UTC
there are some texts could translate in the web ui and Sync Clinet UI
some are not accurate, also you sync character name is wrong when it's unicode.

I know what you do,i want to do the same thing aboout 6 months ago.
a repository  and market like poe trade. I think it's awosome.

What can I do for you, i am able to help.

**Comment by ResurrectedTrader** [comment] 2022-05-10 18:19
Hi,

> there are some texts could translate in the web ui and Sync Clinet UI

Thanks for letting me know, if the translation already exists (it's non-english already), can you please let me know wherethe translation is wrong, potentially with a screenshot with the location?

Also, can you check if there is any text that would be suitable for phrase in the locale files, i.e.:
```
https://resurrected.trade/assets/i18n/strings-<locale>.json
```
 for example
```
https://resurrected.trade/assets/i18n/strings-zhCN.json
```
If yes, let me know the ID, if not, I will mark it to be translated externally (I am still on working setting up translations with transifex.com)

> also you sync character name is wrong when it's unicode.

Can you give me an example of how the character name appears in the UI, and how it should appear correctly, so I can figure out how to fix it? 

> I think it's awosome.

Thanks for the kind words.

> What can I do for you, i am able to help.

I will let you know once localization is available, and how to access it.

I am still working on finalising explanation/demo what this is, how it works etc, but once that is available, it would be nice if you could potentially translate it, spread the word, and potentially share it on some gaming forums/communities local to your region.

A market place with no users is not  a great market.

**Comment by ResurrectedTrader** [comment] 2022-05-10 20:06
I think I fixed the issue with character name localization in the latest release.

**Comment by elmagnificogi** [comment] 2022-05-11 02:05
1. Chinese or Traditional Chinese search cant work.When i type a word then show the right selection,and clear the inputbox and jump to the first selection quickly. So i have to select the item
We also test English and Korean，they are ok

**Comment by elmagnificogi** [comment] 2022-05-11 02:07
2. Character Name not right
![image](https://user-images.githubusercontent.com/10891822/167754359-ed944e49-8ea2-412f-9842-b913befd896c.png)
see the pic ,it's not right Chinese ,like garbled code. English name is ok and the battle id(same with the character name) is ok

**Comment by elmagnificogi** [comment] 2022-05-11 02:10
3.show stash could only show one at same time.and expand account also just one, we want more at same time.
Also we hope could select if show hardcore or classic  at same time

**Comment by elmagnificogi** [comment] 2022-05-11 02:11
4.item PM is not right. when i pm a man with his item, he will receive the message with mine local language not his language (item name)

**Comment by elmagnificogi** [comment] 2022-05-11 02:14
5.ResurrectedTrade-SelfContained.exe sometimes no response and you need wait a long time.
Also when i change character, it may not upload the character info?(firtst time change to the character).Second time ,it's ok

**Comment by elmagnificogi** [comment] 2022-05-11 02:17
6.when i change to Chinese ,there are so many tips that are not translated
![image](https://user-images.githubusercontent.com/10891822/167755462-485b69b7-9b3a-4a94-9939-990a57941d02.png)

i check the file, some word not find.
https://resurrected.trade/assets/i18n/strings-zhCN.json
I think compitable with D2R locale is good .it's easy to sync when game update.
But some word not in game files, maybe we need expand the content

**Comment by elmagnificogi** [comment] 2022-05-11 02:22
7. I know you konw the poe trade, it pm will copy a user name and then communicate in game.I think you could do the same funcs. D2R also could copy user battle id then direct message,so you don't need to implement a communication tools

**Comment by ResurrectedTrader** [comment] 2022-05-11 09:31
1. Thanks for reporting, I will try to reproduce. Can you tell me the set of  keyboard keys I need to press to type the word to filter for "spirit" runeword in traditional chinese?
2. This should already be fixed on the latest version of agent.
3. This is easy to change, but I was trying to avoid the users ending up having a scroll bar. Might change it.
4. This should be fixed by #2 which will render the item client side in his locale, when implemented, so name will be generated at the receiver.
5. Can you check what do the logs say when that happens? And if there are any errors?
6. These strings will be available to translate via transifex.com, I am still in process of setting that up.
7. This does not work, because Blizzard only allows you to send messages to people with who you have been in the same game before. If you never were with that person in a game, its impossible to send messages. Furthermore, I am not sure how Blizzard will react to this project, so showing/giving access to battletags might make it easy for them to collect list of battletags using this project and then ban users. Currently all battletags are hashed.

**Comment by elmagnificogi** [comment] 2022-05-11 13:11
1. you cant seatch spirit， i recommand “ort rune” ，its Chinese is "欧特" （just copy it ，no typing）.Typing Chinese you could select MicroSoft Pinyin Chinese Input in Win10 language ,using American keyboard.
2. I tried yesterday 1.0.15 not right.
3. pass
4. pass
5. I see the log no error, it's add xxx last,but web not sync.when i second joined game .it shows charater add xxxx and so on .Then the web sync
6. pass
7. ok

**Comment by ResurrectedTrader** [comment] 2022-05-11 13:24
1. What would I have to type on american keyboard to get that?
2. 1.0.16 is out since yesterday evening. This will create new characters with the right names, you can right click and delete the old ones that are wrong.

5. Did refreshing the page fix it? I think it might be syncing but the page is just not updating automatically.

**Comment by elmagnificogi** [comment] 2022-05-11 13:29
![image](https://user-images.githubusercontent.com/10891822/167861271-94f15db1-ab88-4fd3-bb00-4fc3533fc898.png)
![image](https://user-images.githubusercontent.com/10891822/167861372-90c2aa1b-81ba-4781-a18e-bf8947ded10c.png)

you just copy my word , it's easy to reproduce

**Comment by elmagnificogi** [comment] 2022-05-11 13:30
3.not refresh,i tried serval times for sync,not work until i rejoin game

**Comment by ResurrectedTrader** [comment] 2022-05-11 13:33
1 It would be good to know what american sound characters to start typing to arrive at those symbols in Kanji, as I think the autocomplete fails while symbols are still in american sounds (before they turn to Kanji).


3 ok, next time this happens, please capture the logs.

**Comment by elmagnificogi** [comment] 2022-05-11 16:11
1.ok，you are right copy cant triggle the bug. “ort rune” ，its Chinese is "欧特符文" （ type: ou te fu wen，maybe you need to select the words）
type: ou te  is enough for “欧特”,search will tip "欧特符文"

**Comment by ResurrectedTrader** [comment] 2022-05-11 19:47
I have now updated the website adding a link help with translations:

https://www.transifex.com/resurrected-trade/resurrected-trade/dashboard/

**Comment by ResurrectedTrader** [comment] 2022-05-11 20:10
I also fixed the autocomplete (I think?)

**Comment by elmagnificogi** [comment] 2022-05-12 03:00
ok，search is ok
![image](https://user-images.githubusercontent.com/10891822/167983054-a9a7cfeb-f4cf-46a0-bc5b-eb39e920ae06.png)
I cant select the language Chinese(China) translation to join , i have to select the Chinese(Taiwan)

**Comment by ResurrectedTrader** [comment] 2022-05-12 08:09
I don't think the language matters, its all the same, you need to create an account and click "help translate" at the top of the page.

**Comment by elmagnificogi** [comment] 2022-05-12 08:14
Let me join first

**Comment by ResurrectedTrader** [comment] 2022-05-12 08:27
I might move the translations to simple github, seems transifex is a bit too complicated for something this simple.

**Comment by elmagnificogi** [comment] 2022-05-12 10:11
ok。I have done first version，could you appliy it, i will do a quick check and fix (some words i dont konw where to display or situation is right)

**Comment by elmagnificogi** [comment] 2022-05-12 10:13
the format i think you could do like D2r ,xxx.json and all language could edit at same time.

**Comment by ResurrectedTrader** [comment] 2022-05-12 10:18
I'll do that in the evening my time today, so you should see it tomorrow morning in your timezone.

**Comment by elmagnificogi** [comment] 2022-05-13 05:30
1.  maybe you make a rong name?
item class is like:axe,armor,belt
item type or tier is like normal,exceptional,elite in MapAssist Define
your translate exchange them.

2. some no translate
![image](https://user-images.githubusercontent.com/10891822/168216279-7bd194ce-7cf4-4acf-aa2f-fb03e95ac499.png)
![image](https://user-images.githubusercontent.com/10891822/168216342-95f5b742-ee6c-49b5-8421-b47117440db2.png)
![image](https://user-images.githubusercontent.com/10891822/168216939-2083920d-6ded-4f8d-85c6-6800eceb26c0.png)
![image](https://user-images.githubusercontent.com/10891822/168217091-b9d362a9-547a-4a17-a911-ef3b07e29aea.png)

**Comment by elmagnificogi** [comment] 2022-05-13 05:30
![image](https://user-images.githubusercontent.com/10891822/168217326-170f945d-73ff-4d98-a361-d9472a7c9c95.png)

**Comment by elmagnificogi** [comment] 2022-05-13 05:31
and what's this? i don't know how it works?
![image](https://user-images.githubusercontent.com/10891822/168217399-f07d0acc-55d9-46e7-a684-fcde07654b1b.png)

**Comment by elmagnificogi** [comment] 2022-05-13 05:35
i have updated all translation,please apply it.

Also i will try to merge your PR in MapAssist  into my MapAssist (Chinese most use my version)

When i check all is ok , i will make a video to my community introducing the trade web

**Comment by ResurrectedTrader** [comment] 2022-05-13 07:25
I will try to fix the untranslatable strings today.

The integration PR might need to be updated as I moved all code to use async, let me know if you need help.

**Comment by elmagnificogi** [comment] 2022-05-13 07:48
when you change to async ,and work done ,tell me. i will merge it from you repository

**Comment by ResurrectedTrader** [comment] 2022-05-13 08:41
So I fixed some strings, I did not fix item type, as that needs a bigger code change as it is generated from enums (I need to work now, hopefully will have time in the evening to fix this).

Let me know where your repository for MA is, I will raise a PR for integration.

Regarding `item type` vs `item class`, these are all user-made terms, so I don't think there is an official name for these.
Would it be better if it was `item type` and `item tier` ?

**Comment by elmagnificogi** [comment] 2022-05-13 10:46
my MapAssit,i change the default language, so you just update your repository,i mege it easier than you.
> https://github.com/elmagnificogi/MapAssist

ok,i think item type and item tier are better

**Comment by elmagnificogi** [comment] 2022-05-13 10:59
ok，updated all translation

**Comment by ResurrectedTrader** [comment] 2022-05-13 19:53
Uploaded new translations that contains the item types.

This is the graph of types in case you need it: https://tinyurl.com/2p8d78ep

**Comment by ResurrectedTrader** [comment] 2022-05-13 19:55
also, there are some features that are not immediately obvious, for example, if you press Ctrl while hovering over item you see the breakdown of stats:

![image](https://user-images.githubusercontent.com/104942311/168380371-3fa498aa-cf3c-49d0-9e0c-87138b8d01c7.png)

**Comment by elmagnificogi** [comment] 2022-05-14 06:03
update all translation，plz apply it， i think the ResurrectedTrade need a label or something that could tell user sync done or synchronizing，use a different icon or a small animation？ i have to see log and wait it.
And it sometimes no response and take 20% more cpu ,MA just 2-5%

**Comment by ResurrectedTrader** [comment] 2022-05-14 10:19
The icon does change color as it syncs, but in theory, if nothing changes in the character it will not sync.



Re cpu usage, does it turn into "not responding"?
What do the logs say around that time?

**Comment by ResurrectedTrader** [comment] 2022-05-14 10:57
I uploaded the translations.

**Comment by elmagnificogi** [comment] 2022-05-14 13:24
when it sync,i click the log window(already show)  then no response........... wait about 1mins or longer ,it recover.

**Comment by elmagnificogi** [comment] 2022-05-14 13:31
![image](https://user-images.githubusercontent.com/10891822/168427915-bcd6fb9b-491a-4db4-904d-e7c0be86880e.png)
could i open more character or more stash？  so many space。 
them could list like ladder and classic and hardcore softcore mode

**Comment by elmagnificogi** [comment] 2022-05-14 13:32
![image](https://user-images.githubusercontent.com/10891822/168427974-634e4fad-5d9d-45b9-91da-9454c7a6d8c8.png)
![image](https://user-images.githubusercontent.com/10891822/168427994-d5473631-f0bc-4b22-80ae-e421d0dfb964.png)
the shield translate is wrong，it's should “盾牌” not "之盾"

**Comment by elmagnificogi** [comment] 2022-05-14 13:42
update translation again

**Comment by ResurrectedTrader** [comment] 2022-05-14 13:44
> when it sync,i click the log window(already show) then no response........... wait about 1mins or longer ,it recover.

what did the logs say around that time?

Maybe I will try to move remote calls to a separate thread. 

Perhaps this is a problem because you have high latency to the servers?

> could i open more character or more stash？ so many space。

It's this way in order to support all resolutions, and to work on mobile. On mobile there is no space.

> them could list like ladder and classic and hardcore softcore mode

Agree filtering might be useful, might add it later, first need to finish introduction material and release it.

> the shield translate is wrong，it's should “盾牌” not "之盾"

Ok changed from 2771 to 2410 in https://resurrected.trade/assets/i18n/strings-zhCN.json

Let me know if any others are wrong.

> update translation again

done

**Comment by elmagnificogi** [comment] 2022-05-14 16:13
![image](https://user-images.githubusercontent.com/10891822/168439964-99f9934c-4aa9-444e-81a6-5e6f376aa6df.png)
it should be  "26130": "在线" not 线上

![image](https://user-images.githubusercontent.com/10891822/168439992-9dcba607-914a-4c7c-b22a-42a5150f9887.png)
only YSE or Any ，where is No？

**Comment by elmagnificogi** [comment] 2022-05-14 16:25
about no response ， when the log window is pringting ， you could try to click it, it must be no response , no matter what it print. 

![image](https://user-images.githubusercontent.com/10891822/168440168-14174ce3-8ac9-46d4-b5e5-465fbbb0c6d6.png)
it's 1574*1030, you could see the space that could contain 2 or 3 character stash.I think PC is different from mobile. More people are use in pc not mobile. Thinking  a mobile user , what he could do ? search a item and leave a note, check his items and set price and more? no . he could only do that, if he sit in pc,he could do all thing through web and more quickly , he doesnt need to leave his mouse and keyboard for operating mobile.

**Comment by ResurrectedTrader** [comment] 2022-05-14 16:49
> it's 1574*1030

I might want to add things like character stats, skills etc, also all of the code is currently written to support only a single character, so it would be a big change. There are more important features, like copy paste items in chat etc.

> about no response ， when the log window is pringting ， you could try to click it, it must be no response , no matter what it print.

Ok, I will try to reproduce by making the connection slow and see if it happens.

> it should be "26130": "在线" not 线上

Should be fixed now.

> only YSE or Any ，where is No？

I don't think it makes sense to look for items of sellers that are ONLY offline.
Why would you ever want that?

I think people want an item NOW, which means online, or they don't care if it's now or later which is Any Online+Offline.

**Comment by elmagnificogi** [comment] 2022-05-14 17:08
No situation : i search a item and use online ,  i saw one good but not ask seller, i want to get a more better . so i continue search , when i check all item , i found that one is the best now . so i back to find it. but the seller offline. so i need offline or i need to research and check all item again?

**Comment by AudriusButkevicius** [comment] 2022-05-14 17:12
But you don't know if the seller is online or offline until you find it again, so it's irrelevant?
The fact someone was online before, doesn't mean that they are offline now...

**Comment by ResurrectedTrader** [comment] 2022-05-14 17:18
But the fact that you found the item before online, doesn't mean it's now offline, so you will have to search through all of them anyway.

**Comment by elmagnificogi** [comment] 2022-05-16 16:24
![(Q`80S`34~HM@G`08HL L](https://user-images.githubusercontent.com/10891822/168639051-7003fe1f-2112-4eb4-b609-fb4ceed92846.png)
The tips no translation

And i have merge your code to my MapAssist.  And test ok

**Comment by elmagnificogi** [comment] 2022-05-16 16:25
Need a syncing or sync ok  label when use MapAssist，is there anything could use for it?

**Comment by elmagnificogi** [comment] 2022-05-16 16:28
There is another proble about CDN, you konw there is a  firewall in China. Some region  visit the web so slow even cant open it.So do you have any plan about it?

**Comment by elmagnificogi** [comment] 2022-05-16 16:31
![image](https://user-images.githubusercontent.com/10891822/168640244-1deff142-046c-4aee-8af3-40a430cbb6a7.png)
the price use double？？ About price should use bitint or some format replace the degit number

**Comment by ResurrectedTrader** [comment] 2022-05-16 19:09
> The tips no translation
Thanks, will try to add a way to translate.

This is coming from server, so might need a bit of code, but I will try to get it done.

> Need a syncing or sync ok label when use MapAssist，is there anything could use for it?

Not sure, there isn't really a good way to show status in MapAssist.
Could show last sync time in the config editor?

But then again, "Sync now" only means "Sync now if there are any changes", as the client tracks for changes, and does not sync if there is no change for example, so the last sync time might be old if the player has not changed (did not move items, etc)

> There is another proble about CDN, you konw there is a firewall in China. Some region visit the web so slow even cant open it.So do you have any plan about it?

I use cloudflare, which I think works as CDN in China?
Is it a problem with loading assets? Or is it a problem with calling the API (api is on separate domain https://api.resurrected.trade), you can check in Chrome developer tools which address not responding, or responding slow.

> the price use double？

Yeah, this looks bad, I will add rounding.

**Comment by ResurrectedTrader** [comment] 2022-05-16 20:28
> The tips no translation

fixed

> the price use double？

fixed

**Comment by elmagnificogi** [comment] 2022-05-17 01:52
CloudFlare is ok.Some of my community loading page are slow, i need some time to check which address

**Comment by elmagnificogi** [comment] 2022-05-17 02:01
Translation done

**Comment by ResurrectedTrader** [comment] 2022-05-17 07:47
updated the translations

**Comment by AudriusButkevicius** [comment] 2022-05-17 08:43
I also wrote up a small wiki on search in English:

https://github.com/ResurrectedTrader/ResurrectedTrade/wiki/Using-search

**Comment by ResurrectedTrader** [comment] 2022-05-17 08:52
There is also a small wiki on search: https://github.com/ResurrectedTrader/ResurrectedTrade/wiki/Using-search

**Comment by elmagnificogi** [comment] 2022-05-17 17:16
![image](https://user-images.githubusercontent.com/10891822/168872391-f19d1692-b0ab-4011-ad13-bc5073f07726.png)
this “image“  "图像" need another translation ”样式“

**Comment by elmagnificogi** [comment] 2022-05-17 17:18
I have publish my MapAssit with Integrations ,so how many user add?

**Comment by ResurrectedTrader** [comment] 2022-05-17 18:12
There are 27 new users, only 19 have uploaded any characters.

**Comment by elmagnificogi** [comment] 2022-05-18 06:12
![image](https://user-images.githubusercontent.com/10891822/168969436-55b3ee4a-1691-42cc-9ff2-8645f571b8c7.png)
add “Graphics” into transifex? i will update it

**Comment by ResurrectedTrader** [comment] 2022-05-18 07:38
Appologies, fixed it now.

**Comment by ResurrectedTrader** [comment] 2022-05-18 19:52
Added flags next to search results to show what locale the player uses to play the game.

To my surprise, it reports that most users (including you) use zh_TW locale, which I think might be incorrect, as I assumed you were from mainland China?

Can you check what is set in registry for `HKEY_CURRENT_USER\SOFTWARE\Blizzard Entertainment\Battle.net\Launch Options\OSI\LOCALE` on your machine? Or is that correct?

**Comment by elmagnificogi** [comment] 2022-05-19 01:00
No, i use zh_CN not TW.
If you use Battle.net Language info ,that's correct. We most play  game use zhTW,but all display of MapAssist  and other software use zhCN.

**Comment by elmagnificogi** [comment] 2022-05-19 02:08
Could you deal the problem that when i change focus to other window, the MapAssist cpu use is high 20%, change to game , it go down to 15%. I think it's because Integration
Pause no use

**Comment by elmagnificogi** [comment] 2022-05-19 02:51
I have reimplement the pause, but the cpu problem i think you should check if it's ok.
The implemention is in my MapAssist main branch

**Comment by AudriusButkevicius** [comment] 2022-05-19 06:51
> If you use Battle.net Language info ,that's correct.

Yes. i use bnet language info, in which case showing TW is correct?

**Comment by ResurrectedTrader** [comment] 2022-05-19 06:53
> If you use Battle.net Language info ,that's correct.

Yes, I use bnet launcher language info, in which case I guess I will just show TW flag, as that seems correct?

**Comment by ResurrectedTrader** [comment] 2022-05-19 07:19
> have reimplement the pause, but the cpu problem i think you should check if it's ok.

I will try to reproduce and see if I can understand whats going on.

**Comment by elmagnificogi** [comment] 2022-05-19 11:23
we most use TW because D2R only support zhTW(when set through battle).IF want to use zhCN,need to change the registry mannually, and when game update all registry will restore. so we are used to  use zhTW.
If you want to get real tag,i think you should try to get from windows display language

**Comment by ResurrectedTrader** [comment] 2022-05-19 12:43
Using os locale is not great, as you'll end up with locales that the game does not support, which is not great.

I think I'll just show the locale that users use for the game, which I guess for zhCN people will sadly be zhTW. 

Interesting that blizzard doesn't persist the zhCN, maybe its a bug on their side?

**Comment by elmagnificogi** [comment] 2022-05-19 15:43
> Interesting that blizzard doesn't persist the zhCN, maybe its a bug on their side?

No, D2R not pass the game censorship in China. And  also online game must be pass then it could release.
Netease will represent D2R in the furture chinese player could only  connect China server(Not Asia)
So only when that day  battle.net will release zhCN for China Battle.net(China Only)
we use Aisa Battle.net(Global),so have to choose zhTW

**Comment by ResurrectedTrader** [comment] 2022-05-19 19:10
Seems the integration doesn't even run in your version:

https://github.com/elmagnificogi/MapAssist/commit/6836702b3dba272a3b05b2bf09211279ad3551b4#diff-bec637de07f0434c84dc78d88d8bbabe4dcd04590981608a8f9c6e7b1c49515fL45

The code that runs was removed as part of the merge?

I don't think the pause code you added does much, as it's not even running, so I don't think the CPU usage is coming from that.

**Comment by ResurrectedTrader** [comment] 2022-05-19 19:36
Raised https://github.com/elmagnificogi/MapAssist/pull/2

**Comment by elmagnificogi** [comment] 2022-05-20 02:47
I tested pause ，it work. when pause the cpu wont go higher when focus on other software

**Comment by elmagnificogi** [comment] 2022-05-20 08:42
> Seems the integration doesn't even run in your version:
But we all sync items? even no run?
I think when focus change , then run one time ?

**Comment by ResurrectedTrader** [comment] 2022-05-20 08:51
Interesting. I would not have expected that. Because Run function is the one that performs the export.

**Comment by ResurrectedTrader** [comment] 2022-05-20 08:52
Let me know if this fixed the cpu usage.

**Comment by elmagnificogi** [comment] 2022-05-20 15:38
it's ok now

**Comment by ResurrectedTrader** [comment] 2022-05-20 19:37
What do you think is the most important thing to work on next?

I was thinking either better listing experience (list value in runes that gets converted to HR float server side), or copy paste items in chat?

**Comment by elmagnificogi** [comment] 2022-05-21 01:55
Could i konw the user number? Chinese user number?

I may make a vidio introducing it tomorrow

> list value in runes that gets converted to HR float server side

I forgot it. The HR value dafault is not right.And ber is 2 and jah 3? In fact , ladder earlier ber is 3 jah is 2. now ber and jah is same. With time gose by, jah is grow.
It's hard to convert rune to a define value. that means every item they sale need to communitcate. And that makes fixed value is meanless.
So i think if they could set rune as unit. like 0.5 ber, 10 ist, if could combine multi of them, that's better, but may be too complex. 

you could see the same trade web ,how they do about it.
> https://traderie.com/diablo2resurrected

Auction mode also is good if you have time to implement it.

**Comment by elmagnificogi** [comment] 2022-05-21 01:58
Also we know the user property，also could share our build ?
Or could we share our stash or some character to friend? let them to find what they want?

**Comment by elmagnificogi** [comment] 2022-05-21 02:01
Too few people use it now. I think it needs a lot of promotion at present.
if many users pour in,how do you deal with the costs of your server and CND? 
There are still many things to consider

**Comment by ResurrectedTrader** [comment] 2022-05-21 10:32
> Could i konw the user number? Chinese user number?

There are 95 registered users, 51 of them are using either TW or CN locale.

> I may make a vidio introducing it tomorrow

You can see my demo video in the github readme of what I showed.

> I forgot it. The HR value dafault is not right.And ber is 2 and jah 3? In fact , ladder earlier ber is 3 jah is 2. now ber and jah is same. With time gose by, jah is grow.

Yeah I know that, but there is no good source of the exchange rates to have this accurate over time in different game modes.

> you could see the same trade web ,how they do about it.

yeah, that's what I plan to do, but will not have time this weekend.

> Also we know the user property，also could share our build ?

When you mean build, I assume you mean, your inventory?
Currently we don't sync character skill levels, but we could.

> Or could we share our stash or some character to friend? let them to find what they want?

The backend supports it (you can mark character or bnet account as public), I just have not exposed that in the UI, but I plan to add that some time later.

> Too few people use it now. I think it needs a lot of promotion at present.
> if many users pour in,how do you deal with the costs of your server and CND?

Agree, there aren't that many users now so it's not very useful.

The CDN is free, my server also has unlimited bandwidth, and I am paying for it already anyway for my personal stuff.

I tested the system with a hundred thousand characters and a few million items and it was fine, the search might start slowing down, and we might have to prevent search with no filters, but in general, I would love to have a problem like this :) at the moment it does not exist.

**Comment by elmagnificogi** [comment] 2022-05-25 01:49
There is a problem that the Sync cant stop???
I have pause it. Could you check it?
Many people feedback it use too many cpu when open.

**Comment by ResurrectedTrader** [comment] 2022-05-25 13:21
I saw your added the pause flag, so I assume cpu usage problem is still there?

Did adding the pause actually help?

**Comment by elmagnificogi** [comment] 2022-05-25 13:37
i solved

**Comment by ResurrectedTrader** [comment] 2022-05-25 14:03
It seems its still paused by default even if the user is logged in?

**Comment by elmagnificogi** [comment] 2022-05-25 14:57
No,base on their registy last time.

**Comment by ResurrectedTrader** [comment] 2022-05-25 14:59
Right, but I guess if they log in for the first time, it will be paused, which might be unexpected?

**Comment by elmagnificogi** [comment] 2022-05-25 15:17
i have a guide doc say it how to work

**Comment by ResurrectedTrader** [comment] 2022-05-27 22:16
Added support making characters/accounts public via right click menu, you can then copy the url and pass it to someone else.

Also updated the listing system to be more like traderie.io, where you have 3 prices, with 3 units each, and prices are displayed in search results.

Still need to update search price filters (to filter by unit, not by float)

**Comment by elmagnificogi** [comment] 2022-05-28 15:58
![image](https://user-images.githubusercontent.com/10891822/170833083-bc11d91c-b5f6-46c2-84bf-7e8943711aeb.png)
it's hard to konw how much it is.

![image](https://user-images.githubusercontent.com/10891822/170833101-66a011c4-a097-4333-8568-283ef4a98b16.png)
could rune with num? like 24+25  32+33?

**Comment by elmagnificogi** [comment] 2022-05-28 16:00
And the country ,could select by player ? not by auto recognize? like me ,it's TW flag,not right.

**Comment by elmagnificogi** [comment] 2022-05-28 16:14
It's not reasonable and you set 3 units, why not no limit ?

**Comment by ResurrectedTrader** [comment] 2022-05-28 16:41
> it's hard to konw how much it is.

This is only for items that were listed before I added the support for specifying runes.

> could rune with num? like 24+25 32+33?

I personally recognise the images, I have no idea what numbers they are.
If someone told me 24+25, I'd have no idea what it would be, however I do know Ist+Mal etc.

Why do you think this would be better?
I don't think other sites list numbers? They are not used in JSP either.

> And the country ,could select by player ? not by auto recognize? like me ,it's TW flag,not right.

It's using the locale of the client. 

I can't use the language of the OS either, because if someone is in India, showing an Indian flag would't be useful, as there is 
no translated strings to Indian, and it's not clear what locale the Indian player is using, so that you would know what language to communicate in.

I guess I can hide the flags, or perhaps add support checking OS language if game locale is TW and if it's ZH, use ZH locale?

> It's not reasonable and you set 3 units, why not no limit ?

I think having too many prices/components to the price makes it hard to interpret the price "at a glance".
If you scroll through 10's of items, you want it to be easy to understand what you are looking at.

**Comment by ResurrectedTrader** [comment] 2022-05-28 16:42
Can you check what `CultureInfo.CurrentUICulture.Name` and   `CultureInfo.CurrentUICulture.EnglushName`  in C# returns on your machine?

**Comment by elmagnificogi** [comment] 2022-05-29 04:35
You could auto recgnize local, i mean you could give a setting UI  in web to change it?

**Comment by elmagnificogi** [comment] 2022-05-29 04:37
it return:
zh-CN
Chinese (Simplified, China)

**Comment by ResurrectedTrader** [comment] 2022-05-30 20:14
Added a workaround which uses OS language if locale is TW, and if zhCN, reports as zhCN and shows Chinese flag.
Raised PR in your repo updating to latest version that has this fix.

Also added tooltip as suggested:

![image](https://user-images.githubusercontent.com/104942311/171054690-3848c77c-cf43-4f14-b463-cf015203d79a.png)

**Comment by elmagnificogi** [comment] 2022-05-31 16:03
It work ,just need logout and login

**Comment by ResurrectedTrader** [comment] 2022-05-31 22:13
I think you need something to change on the char for it to update.

**Comment by elmagnificogi** [comment] 2022-06-06 07:27
update translation

**Comment by ResurrectedTrader** [comment] 2022-06-06 07:28
Uploaded.

**Comment by ResurrectedTrader** [comment] 2022-06-06 08:13
Updated translations adding some missing strings from right click menu.

**Comment by elmagnificogi** [comment] 2022-06-06 13:39
Done

**Comment by ResurrectedTrader** [comment] 2022-06-06 14:14
Rolled out.

**Comment by elmagnificogi** [comment] 2022-06-15 02:18
All accounts use MA have been baned，i think the project should stop

**Comment by ResurrectedTrader** [comment] 2022-06-15 20:35
Well, there is nothing to "stop". Most users came via your integration, so it has stopped naturally :) Condolences to your users.

Sadly, the private bot farms continue to live untouched.

**Closed as completed** 2022-09-29 19:59 UTC
Labels: enhancement, ui, agent
